# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import autogen.election_pb2 as election__pb2


class ElectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateElection = channel.unary_unary(
        '/Election/CreateElection',
        request_serializer=election__pb2.CreateElectionRequest.SerializeToString,
        response_deserializer=election__pb2.CreateElectionResponse.FromString,
        )
    self.GetElection = channel.unary_unary(
        '/Election/GetElection',
        request_serializer=election__pb2.GetElectionRequest.SerializeToString,
        response_deserializer=election__pb2.GetElectionResponse.FromString,
        )
    self.UpdateElection = channel.unary_unary(
        '/Election/UpdateElection',
        request_serializer=election__pb2.UpdateElectionRequest.SerializeToString,
        response_deserializer=election__pb2.UpdateElectionResponse.FromString,
        )
    self.RemoveElection = channel.unary_unary(
        '/Election/RemoveElection',
        request_serializer=election__pb2.RemoveElectionRequest.SerializeToString,
        response_deserializer=election__pb2.RemoveElectionResponse.FromString,
        )
    self.GetElections = channel.unary_unary(
        '/Election/GetElections',
        request_serializer=election__pb2.GetElectionsRequest.SerializeToString,
        response_deserializer=election__pb2.GetElectionsResponse.FromString,
        )


class ElectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateElection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetElection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateElection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveElection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetElections(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ElectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateElection': grpc.unary_unary_rpc_method_handler(
          servicer.CreateElection,
          request_deserializer=election__pb2.CreateElectionRequest.FromString,
          response_serializer=election__pb2.CreateElectionResponse.SerializeToString,
      ),
      'GetElection': grpc.unary_unary_rpc_method_handler(
          servicer.GetElection,
          request_deserializer=election__pb2.GetElectionRequest.FromString,
          response_serializer=election__pb2.GetElectionResponse.SerializeToString,
      ),
      'UpdateElection': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateElection,
          request_deserializer=election__pb2.UpdateElectionRequest.FromString,
          response_serializer=election__pb2.UpdateElectionResponse.SerializeToString,
      ),
      'RemoveElection': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveElection,
          request_deserializer=election__pb2.RemoveElectionRequest.FromString,
          response_serializer=election__pb2.RemoveElectionResponse.SerializeToString,
      ),
      'GetElections': grpc.unary_unary_rpc_method_handler(
          servicer.GetElections,
          request_deserializer=election__pb2.GetElectionsRequest.FromString,
          response_serializer=election__pb2.GetElectionsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Election', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
